nelmio_api_doc:
    documentation:
        host: 127.0.0.1:8000
        schemes: [http, https]
        info:
            title: Jobeet
            description: This is an awesome app!
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []