security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_users_provider:
            entity:
                # the class of the entity that represents users
                class: 'App\Entity\User\User'

    encoders:
        App\Entity\User\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_EMPLOYER: ROLE_USER
        ROLE_APPLICANT: ROLE_USER
        ROLE_ADMIN: [ROLE_EMPLOYER, ROLE_APPLICANT, ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: app_users_provider
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   app_logout
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
