# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm
    mappings:
        job_image:
            uri_prefix: /uploads/jobs
            upload_destination: '%kernel.project_dir%/public/uploads/jobs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true